### ISSUE TITLE
What should happen when I visit mongodb.design?

### ISSUE THREAD

**Issue by pzrq** [mongodb/design#85]
Following the [mongodb.design](http://mongodb.design/) link in the [README](https://github.com/mongodb/design#documentation), I see the following in Chrome 62.0.3202.94 on macOS High Sierra (10.13.1):

![screen shot 2017-11-20 at 1 32 55 pm](https://user-images.githubusercontent.com/1217010/32999650-6ede9a00-cdf7-11e7-8907-34c73403f424.png)

What should I see?

Or is this link out of date and should it be removed?

**Comment by marcgurney** [comment]
@pzrq The readme file has been updated to point to the correct URL: https://mongodb.github.io/design

We'll point to mongodb.design after sufficient QA and polish. 

Sorry for the (super) late reply! Didn't get a notification about this issue.

**Comment by pzrq** [comment]
@marcgurney Thanks for the update, I look forward to it 👍 

P.S. No worries - GitHub notifications can a bit of a black art 🍻

**Comment by pzrq** [comment]
![lgtm](https://user-images.githubusercontent.com/1217010/36581126-8a8785a6-18bf-11e8-9ff1-ad0d64faf33c.png)
